<?php
    function image_test_menu() {
        $items['image_test']=array(
            'title' => 'image test',
            'page callback'=>'image_display',
            'access callback'=>TRUE,
            'type'=> MENU_NORMAL_ITEM,
        );
        return $items;
    }

    function image_display() {
        return '<img src="https://i.ytimg.com/vi/-5fKvN-RwKs/hqdefault.jpg">Tsunami!</img>';
    }

    
